#just some deb-get installs 
sudo deb-get install google-chrome-stable   
sudo deb-get install bitwarden
sudo deb-get install brave-browser
sudo deb-get install codium
sudo deb-get install foliate
sudo deb-get install keepassxc
sudo deb-get install signal-desktop
sudo deb-get install sublime-text
sudo deb-get install ulauncher
sudo deb-get install virtualbox-6.1
sudo deb-get install nordvpn
