#!/bin/bash
set -e
source all_installer_list.sh
CLEAN_UPDATE 
FIRST_UPGRADE
ENABLE_FLATPAKS
#REBOOT_SYSTEM
INSTALL_BASIC_UTILITIES
#-----------Terminal makeup---------------------# 
INSTALL_PFETCH
INSTALL_MICROSOFT_FONTS
INSTALL_POWERLINEFONTS
COPY_BASHRC_AND_BASH_ALIASES
#--------------Beautification------------------#
INSTALL_DRACULA_GEDIT
INSTALL_DRACULA_GTK_THEME
INSTALL_DRACULA_GNOME_TERMINAL
INSTALL_PAPIRUS_ICON_THEME
#---------------Browsers------------------------#
INSTALL_GOOGLECHROME
INSTALL_EDGEBROWSER
INSTALL_BRAVEBROWSER
INSTALL_WATERFOX
INSTALL_LIBREWOLF  #Flatpak
INSTALL_CHROMIUM   #Flatpak
INSTALL_TORBROWSER #Flatpak
#INSTALL_MIDORI     #Flatpak
#INSTALL_VIVALDIBROWSER
#INSTALL_OPERABROWSER
CLEAN_UPDATE
FIRST_UPDATE
REBOOT_SYSTEM







